### ISSUE TITLE
Interactivity checklist

### ISSUE THREAD

**Issue by OctarineSourcerer** [OctarineSourcerer/cyberpunk2020-foundry#15]
- [x] Editable name, age, etc.
- [x] Editable stat base and mod, calculate new
- [x] Set current wound track
- [x] Edit skill value, chipped
- [x] Sort skills
- [x] Search skills
- [x] Roll skills
- [x] Equip/unequip items

**Comment by drowzero0** [comment]
i would only add 1 point to that list if its about interactivity in lists.
lots of my players have loads of items. but they do not have every item carrying.
a boolean for if an item is currently worn or not would be great!
like that the ppl can decide for themself if the item is in their backpack and do not need to modfy the item itself by a notice or having the items listed extra in the Life - list.

Skillsorting and rollable skills seems to work now as shown in your list above.

**Comment by OctarineSourcerer** [comment]
> i would only add 1 point to that list if its about interactivity in lists.
> lots of my players have loads of items. but they do not have every item carrying.
> a boolean for if an item is currently worn or not would be great!
> like that the ppl can decide for themself if the item is in their backpack and do not need to modfy the item itself by a notice or having the items listed extra in the Life - list.
> 
> Skillsorting and rollable skills seems to work now as shown in your list above.

Items being equipped should now be a thing :) Whether they're equipped or not governs whether they affect stats, armor etc. They still appear on the sheet though, in all places including combat. I might see about indicating in some way that they're not equipped currently - either excluding them from the gear tab or greying them out in some way.
